server:
  port: 81

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: false
#设置feign客户端超时时间
ribbon:
  #建立连接可用的时间
  ReadTimeout: 5000
  #  获取数据的链接超时时间
  ConnectTimeout: 5000
logging:
  level:
    com.wei.service.PaymentFeignService: debug
